version: '3.4'

services:
  mediahub:
    image: ${DOCKER_REGISTRY-}mediahub
    build:
      context: .
      dockerfile: MediaHub/Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "SA1234567!s"
      ACCEPT_EULA: "Y"

