image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - 'echo | dotnet --version'
  script:
    - echo "Building the application"
    - dotnet build MediaHub/MediaHub.sln
    - echo "Preparing Project"
    - dotnet publish MediaHub/MediaHub.sln -c release
  artifacts:
    paths:
      - "MediaHub/MediaHub/bin/*"
    expire_in: 1 week

unit-test-job:   
  stage: test 
  script:
    - echo "Currently there are no unti testings in place."

docker-build:  
  stage: build
  image: docker:latest 
  services:
    - docker:dind
  artifacts:
    paths:
      - src/App/bin/release
  before_script:
    - echo $CD_KEY_GITLAB | docker login -u "$CD_USERNAME_REGISTRY" --password-stdin CI_REGISTRY
  script:
    - docker build --pull -f ./MediaHub/Dockerfile -t registry.gitlab.ost.ch:45023/seproj/2022-fs/g04-mediahub/code/mediahub .
    - docker push registry.gitlab.ost.ch:45023/seproj/2022-fs/g04-mediahub/code/mediahub
    - docker logout
  only:
    - cd

