image: mcr.microsoft.com/dotnet/sdk:6.0

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  only:
      - main
  before_script:
      - 'echo | dotnet --version'
  script:
    - echo "Building the application"
    - dotnet build MediaHub/MediaHub.sln
  artifacts:
    paths:
      - "MediaHub/bin/"
    expire_in: 1 week

unit-test-job:   
  stage: test 
  script:
    - echo "Currently there are no unti testings in place."

deploy-job:  
  stage: deploy 
  artifacts:
    paths:
      - src/App/bin/release
  script:
    - echo "Preparing the deployment to the test server"
    - echo "Loging into docker registry"
    - docker login registry.gitlab.ost.ch:45023 -u $CD_USERNAME_REGISTRY -p $CD_KEY_GITLAB
    - echo "Preparing Project"
    - dotnet publish MediaHub/MediaHub.sln -c release
    - docker build -f ./MediaHub/Dockerfile -t registry.gitlab.ost.ch:45023/seproj/2022-fs/g04-mediahub/code/mediahub .
    - docker push registry.gitlab.ost.ch:45023/seproj/2022-fs/g04-mediahub/code/mediahub
    - docker logout
  dependencies:
    - build
  only:
    - cicd

