version: '3.4'

services:

  mediahub:
    image: registry.gitlab.ost.ch:45023/seproj/2022-fs/g04-mediahub/code/mediahub
    ports:
      - 80:80
    depends_on:
        - db
        
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "SA1234567!s"
      ACCEPT_EULA: "Y"
