version: '3.4'

services:
  mediahub:
    image: mediahubapplication
    container_name: mediahub
    ports:
      - 80:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: db
    environment:
      SA_PASSWORD: "SA1234567!s"
      ACCEPT_EULA: "Y"
